code --install-extension alexcvzz.vscode-sqlite
code --install-extension alexdima.copy-relative-path
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension jchannon.csharpextensions
code --install-extension jmrog.vscode-nuget-package-manager
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mauve.terraform
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension mhartington.oceanic-next
code --install-extension mikestead.dotenv
code --install-extension mrmlnc.vscode-duplicate
code --install-extension ms-python.python
code --install-extension ms-vscode.csharp
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension msjsdiag.vscode-react-native
code --install-extension mushan.vscode-open-iterm2
code --install-extension octref.vetur
code --install-extension sdras.vue-vscode-snippets
code --install-extension sysoev.language-stylus
code --install-extension WallabyJs.quokka-vscode
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.ReactSnippets
